package com.nxedu.haircutreserve.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.nxedu.haircutreserve.bean.User;
import com.nxedu.haircutreserve.bean.MeData;

import com.nxedu.haircutreserve.dao.UserDao;
import com.nxedu.haircutreserve.dao.MeDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig meDataDaoConfig;

    private final UserDao userDao;
    private final MeDataDao meDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        meDataDaoConfig = daoConfigMap.get(MeDataDao.class).clone();
        meDataDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        meDataDao = new MeDataDao(meDataDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(MeData.class, meDataDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        meDataDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public MeDataDao getMeDataDao() {
        return meDataDao;
    }

}
